language: node_js
cache:
  yarn: true
yarn: true
notifications:
  email: false
node_js:
  - '10'
  - '8'
script:
  - yarn test && yarn travis-deploy-once "yarn semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
